### ISSUE TITLE
AttributeError: Unable to convert the pixel data: one of Pixel Data, Float Pixel Data or Double Float Pixel Data must be present in the dataset

### ISSUE THREAD

**Issue by liam-ot** [TCIA-Community/TCIA-API-SDK#7] opened 2020-12-18 22:40 UTC
Hello, I have an issue with a dataset object returning the error:
`AttributeError: Unable to convert the pixel data: one of Pixel Data, Float Pixel Data or Double Float Pixel Data must be present in the dataset`

The error is generated by:
```
for i in range(10):
    jpg=images[i].replace('.dcm', '.jpg')
    with dicom.dcmread(images[i]) as info:
        info.file_meta.TransferSyntaxUID = '1.2.840.10008.1.2.2'
        arr=info.pixel_array       #error occurs here
        print(arr)
```

ignore the `jpg` var, at this point I am simply attempting to extract the `pixel_array` of the DCM objects I have obtained from TCIA, `images` is an array of paths to the DCM images and I had to manually set the `TransferSyntaxUID` to one of the pre-set `-endians`.

**Comment by pradeeban** [comment] 2020-12-18 22:43
Hi,
I am trying to understand what you are doing.

If I understand correctly, the bug is produced by your DICOM to JPG converter, and not related to the TCIA-API. right?

What is the TCIA-API bug here?

**Comment by liam-ot** [comment] 2020-12-18 22:45
It seems like somehow the DCM object I pulled in from TCIA does not contain a `pixel_array` attr, I can attach one of the files?

**Comment by pradeeban** [comment] 2020-12-18 22:53
Several scenarios:
(1) Your DICOM -> JPG converter is buggy.
(2) The DCM image you downloaded doesn't have a pixel_array object (as you suspected), which is not a bug of TCIA-API-SDK, which just pulls the images from TCIA.

I believe (1) is more likely (a bug in the code or a missing dependency such as gdcm). I would recommend you to use https://github.com/Emory-HITI/Niffler/tree/master/modules/png-extraction on the image to do the DCM -> PNG conversion and check whether you still encounter the same error.

If you still encounter the same error, (2) could be the reason. But that could be just a missing image/binary in the DICOM object (i.e., not a bug. rather, that is what TCIA has for that particular DICOM). Check again whether you will have the same error from other DICOM images that you have downloaded.

In both cases, this is not a bug of the TCIA-API-SDK which is merely an API to invoke TCIA.

I am closing this bug report.

**Closed as completed by pradeeban** 2020-12-18 22:53 UTC
Labels: invalid

**Comment by liam-ot** [comment] 2020-12-18 23:01
okay, thank you, it must be 2 because that is the whole snippet of code, there is no other conversion going on, in fact maybe you could answer this question for me, the reason I was doing conversion at all was to feed the image to a neural net as a jpg, but I was thinking I can just pass it this pixel_array. Is there any reason a numpy array from a dcm image would be different than that of the jpg version of that image? If you don't know that's fine, please let me know and I will ask in another place, thanks again

**Comment by pradeeban** [comment] 2020-12-18 23:07
We have had some issues in the past to convert to jpg as well. But png conversion was more smooth. Besides, it could be a jpeg-lossless compressed image, that would require gdcm installed as a dependency.

Hence, my suggestion to try:
1. Niffler (the link I shared) to convert the same image into png and see whether you are still failing. (in that case, you will have already installed gdcm as a dependency). In that case, the issue is with your code.
2. Try some other images downloaded from TCIA with your code to see whether you still have the same problem. In that case, it just a missing DICOM from that particular image. Other images should work.

Niffler with random dicom images downloaded from TCIA worked.

I hope that helps.
